### ISSUE TITLE
android-safetynet

### ISSUE THREAD

**Issue by OperKH** [webauthn-open-source/fido2-server-demo#17]
Doesn't with fingerprint.

> Error: registration failed: no support for attestation format: android-safetynet
> Registration error: Error: registration failed: no support for attestation format: android-safetynet

**Comment by hkurokawa** [comment]
I am wondering this might be because [fido2-lib](https://github.com/apowers313/fido2-lib) does not support Android SafetyNet API as an attestation format.  [The change to support the format](https://github.com/apowers313/fido2-lib/commit/88fb933f394e13652602fe4457571ba2290e2b6d) seems already in the master branch but a newer version of fido2-lib seems not released yet.

**Comment by Sami32** [comment]
I've saw it using the latest Opera on Android 7.0 while having select the alternative pattern method.

As a side note this same method worked fine using Firefox 68.3.

**Comment by JamesCullum** [comment]
Updated in fido2-lib
