### ISSUE TITLE
https://webauthn.org/Certificate Expired

### ISSUE THREAD

**Issue by jwilleke** [webauthn-open-source/fido2-server-demo#28]
Expired: Sunday, June 16, 2019 at 09:45:01 Eastern Daylight Time

**Comment by JamesCullum** [comment]
The website is not maintained anymore

**Comment by collinanderson** [comment]
Should links be removed that point to webauthn.org? There are a few references to webauthn.org in this repository, and MDN also links to webauthn.org. https://developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API

**Comment by JamesCullum** [comment]
Generally it'd be appreciated if you can create a PR with those removed. In the main repository we are using the OWASP SSO as example. However - the people nominated for the group (webauthn-open-source) sadly lack access to maintain this repository - only @apowers313 can merge. As he is inactive, this might take a while.

**Comment by apowers313** [comment]
Is there a way for me to grant perms?

**Comment by JamesCullum** [comment]
The issue was the base permission for the organization - I noticed that you changed my permission to properly manage the org as well, so I was able to change the base permissions as well.

So good news - we should now be able to write to this repository as well. Will take care of the PR, thanks a lot!
