### ISSUE TITLE
SSL error

### ISSUE THREAD

**Issue by tvlooy** [webauthn-open-source/fido2-server-demo#7]
The certificate chain on webauthn.org is incomplete. I noticed because FIrefox mobile won't load your site. See also https://www.ssllabs.com/ssltest/analyze?d=webauthn.org

**Comment by apowers313** [comment]
Are you talking about the lack of DNS CAA?

<img width="555" alt="image" src="https://user-images.githubusercontent.com/5661534/41810847-dbd5f62e-76b9-11e8-89a7-c4c44f079340.png">

**Comment by tvlooy** [comment]
No the "chain issue incomplete". You didn't install the full chain in the vhost of the website. Eg: in Apache this is SSLCertificateChainFile and must contain all intermediate certificates. Mobile browser can come with a limited set of these certificates so that is why this is a  issue on firefox mobile but not on the desktop

**Comment by apowers313** [comment]
Got it, I missed the "mobile" part of the issue. Thanks for reporting this, I'll see if I can duplicate it and fix it.

For what it's worth, I don't think any mobile browsers support WebAuthn yet. I think we are going to get past this issue just so you can see an error message pop up that says "WebAuthn isn't supported by this browser".

Still obviously worth fixing for when mobile support comes around (probably later this year)...

**Comment by tvlooy** [comment]
Okay. And thanks for the test site!

**Comment by thierrycoopman** [comment]
The MacOs version of Firefox also doesn't want to load the test site due to an incomplete certificate chain.

SSLlabs has more info

https://www.ssllabs.com/ssltest/analyze.html?d=webauthn.org

2 | Extra download | Let's Encrypt Authority X3 Fingerprint SHA256: 25847d668eb4f04fdd40b12b6b0740c567da7d024308eb6c2c96fe41d9de218dPin SHA256: YLh1dUR9y6Kja30RrAn7JKnbQG/uEtLMkBgFF2Fuihg= RSA 2048 bits (e 65537)	/ SHA256withRSA
-- | -- | --

Also, when on this topic, please turn off if possible TLS 1.0 and 1.1 and weak cyphers.

**Comment by JamesCullum** [comment]
The website is not maintained anymore
